sdk:
- main

os:
- linux
- windows

stages:
- analyze_and_format:
  - analyze: --fatal-infos .
    os: linux
- unit_test:
  - command: dart run build_runner test --enable-experiment=macros -- -p chrome --test-randomize-ordering-seed=random
  # TODO(https://github.com/dart-lang/build/issues/3423): restore this on windows
  - command: dart run build_runner test --enable-experiment=macros -- -p vm test/configurable_uri_test.dart --test-randomize-ordering-seed=random
    os: linux
- e2e_test:
  - test: --enable-experiment=macros --total-shards 3 --shard-index 0 --test-randomize-ordering-seed=random
    os: linux
  - test: --enable-experiment=macros --total-shards 3 --shard-index 1 --test-randomize-ordering-seed=random
    os: linux
  - test: --enable-experiment=macros --total-shards 3 --shard-index 2 --test-randomize-ordering-seed=random
    os: linux
  - test: --enable-experiment=macros --total-shards 3 --shard-index 0 --test-randomize-ordering-seed=random
    os: windows
  - test: --enable-experiment=macros --total-shards 3 --shard-index 1 --test-randomize-ordering-seed=random
    os: windows
  - test: --enable-experiment=macros --total-shards 3 --shard-index 2 --test-randomize-ordering-seed=random
    os: windows
# This stage is configured to only run for scheduled builds (see mono_repo.yaml)
- e2e_test_cron:
  - test:
    sdk:
    - be/raw/latest
